# Customer Revenue and Retention Analytics

**Project Type:** Business Data Analytics  
**Dataset:** UCI Online Retail II  
**Business Domain:** Retail and E-commerce  
**Study Period:** 2009–2011

## 1. Project Objective

The objective of this project is to analyze historical retail transactions to understand revenue performance, customer purchasing behavior, repeat purchasing, product contribution, geographic market performance, and sales trends.

The analysis aims to identify actionable business insights and opportunities to improve revenue generation, customer retention, and overall business performance.

## 2. Business Questions

### A. Revenue and Sales Performance

1. How has the retailer's revenue changed over time, and what are the major sales trends?
2. Which months, quarters, and periods generate the highest and lowest revenue?
3. What is the overall sales performance across the available dataset period?

### B. Customer Revenue and Value

4. Which customers contribute the most to total revenue?
5. How concentrated is revenue among the highest-spending customers?
6. What is the average revenue generated per customer, and how does customer spending vary?

### C. Customer Purchasing Behavior and Retention

7. How many unique customers made purchases during the study period?
8. How many customers made repeat purchases, and what proportion of customers returned to purchase again?
9. How frequently do customers purchase, and what is the typical time between their purchases?
10. How does customer purchasing activity change over time?
11. Are there customers whose purchasing activity declines or stops, indicating possible customer attrition?

### D. Product Performance

12. Which products generate the highest revenue?
13. Which products sell the highest quantities, and do high sales volumes correspond to high revenue?
14. Which products contribute the least revenue, and what opportunities for improvement can be identified?

### E. Geographic and Market Performance

15. Which countries contribute the most to total revenue?
16. How does customer purchasing behavior and revenue contribution differ across countries?
17. Which markets present potential opportunities for revenue growth?

### F. Cancellations and Data Quality

18. What proportion of recorded transactions involve cancellations or returns, where these can be identified from the available data?
19. How do cancellations and returned quantities affect reported sales revenue?
20. What data quality issues, including missing customer identifiers, unusual quantities, invalid prices, and duplicate records, could affect the reliability of our findings?

### G. Business Recommendations

21. Which customer groups or purchasing patterns should the retailer prioritize to improve customer retention?
22. Which products, periods, and markets offer the strongest opportunities for improving revenue?
23. What practical, evidence-based recommendations can be made to improve revenue performance and encourage repeat purchasing?

## 3. Expected Project Outcomes

- Assess the quality and reliability of the dataset.
- Analyze revenue performance and sales trends.
- Identify high-value customers and key revenue-generating products.
- Measure repeat purchasing and customer retention.
- Evaluate geographic market performance.
- Assess cancellations and their impact on reported revenue.
- Develop evidence-based business insights and actionable recommendations.
- Build a professional Power BI dashboard.
- Publish a documented, reproducible project in a GitHub portfolio repository.

## 4. Analytical Workflow

1. **Dataset Inspection:** Understand the dataset structure, variables, date range, and data quality.
2. **Excel Analysis:** Conduct initial exploration, calculations, summaries, and visualizations.
3. **SQL Analysis:** Analyze transactions, revenue, customers, products, and geographic markets.
4. **Python Analysis:** Perform exploratory data analysis, customer behavior analysis, and validation.
5. **Power BI Reporting:** Develop an interactive dashboard presenting key metrics and insights.
6. **Final Reporting:** Document findings, explain business implications, acknowledge limitations, and provide recommendations.

## 5. Analytical Principles

- Business questions will guide the analysis.
- Data cleaning decisions will be documented and justified.
- Revenue calculations will account for transaction quantities, prices, cancellations, and returns.
- Repeat purchasing and customer retention will be treated as related but distinct concepts.
- Customer inactivity will not automatically be interpreted as permanent customer loss.
- Findings will be validated before being reported.
- Assumptions, limitations, and data quality issues will be documented.
- Recommendations will be based on evidence from the analysis.

## 6. Final Deliverable

The final deliverable will be a professional business analytics portfolio project demonstrating the ability to inspect and prepare transaction data, investigate business questions, use Excel, SQL, Python, and Power BI appropriately, validate results, communicate insights, and translate analytical findings into practical business recommendations.

In [5]:
print("Business Analytics notebook is working!")
print("python is ready")

Business Analytics notebook is working!
python is ready

In [ ]:
import pandas as pd
df = pd.read_excel("Online Retail.xlsx")
df.head()

In [ ]:
df.shape
df.info()
df.isnull().sum()

<class 'pandas.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  object
 1   StockCode    541909 non-null  object
 2   Description  540455 non-null  object
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  datetime64[us]
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  str
dtypes: datetime64[us](1), float64(2), int64(1), object(3), str(1)
memory usage: 33.1+ MB

InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

### Dataset Structure and Initial Missing-Value Assessment

**Objective:** Inspect the raw dataset's dimensions, column structure, data types, memory usage, and initial missing-value distribution.

#### Findings

- The dataset contains **541,909 records and 8 columns**.
- The `Description` column contains 1,454 missing values.
- The `CustomerID` column contains 135,080 missing values.
- The remaining six columns contain no missing values according to the initial assessment.
- The `InvoiceDate` column is stored as a datetime, `Quantity` as an integer, and `UnitPrice` as a floating-point number.
- The dataset uses approximately 93.1 MB or more of memory.

#### Interpretation

Missing customer identifiers may limit customer-level revenue and retention analysis. Missing product descriptions may affect product-level reporting. These issues require further investigation before cleaning decisions are made.

#### Decision

Preserve the raw dataset. Do not delete records or fill missing values at this stage. Investigate missing values, duplicates, cancellations, unusual quantities, prices, and data types before establishing cleaning rules.

#### Status

Initial dataset inspection completed. Detailed data-quality assessment pending.

In [ ]:
print(df.shape)
print(df.duplicated().sum())
print((df["Quantity"] <=0).sum())
print((df["UnitPrice"] <= 0).sum())
print(df["InvoiceNo"].astype(str).str.startswith("C").sum())

(541909, 8)
5268
10624
2517
9288

In [ ]:
# Inspect transactions with non-positive quantities
display(df[df["Quantity"] <= 0].head(10))

# Inspect transactions with non-positive unit prices
display(df[df["UnitPrice"] <= 0].head(10))

# Inspect invoices starting with C
display(
    df[df["InvoiceNo"].astype(str).str.startswith("C")].head(10)
)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
141,C536379,D,Discount,-1,2010-12-01 09:41:00,27.50,14527.0,United Kingdom
154,C536383,35004C,SET OF 3 COLOURED FLYING DUCKS,-1,2010-12-01 09:49:00,4.65,15311.0,United Kingdom
235,C536391,22556,PLASTERS IN TIN CIRCUS PARADE,-12,2010-12-01 10:24:00,1.65,17548.0,United Kingdom
236,C536391,21984,PACK OF 12 PINK PAISLEY TISSUES,-24,2010-12-01 10:24:00,0.29,17548.0,United Kingdom
237,C536391,21983,PACK OF 12 BLUE PAISLEY TISSUES,-24,2010-12-01 10:24:00,0.29,17548.0,United Kingdom
238,C536391,21980,PACK OF 12 RED RETROSPOT TISSUES,-24,2010-12-01 10:24:00,0.29,17548.0,United Kingdom
239,C536391,21484,CHICK GREY HOT WATER BOTTLE,-12,2010-12-01 10:24:00,3.45,17548.0,United Kingdom
240,C536391,22557,PLASTERS IN TIN VINTAGE PAISLEY,-12,2010-12-01 10:24:00,1.65,17548.0,United Kingdom
241,C536391,22553,PLASTERS IN TIN SKULLS,-24,2010-12-01 10:24:00,1.65,17548.0,United Kingdom
939,C536506,22960,JAM MAKING SET WITH JARS,-6,2010-12-01 12:38:00,4.25,17897.0,United Kingdom

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
622,536414,22139,NaN,56,2010-12-01 11:52:00,0.0,NaN,United Kingdom
1970,536545,21134,NaN,1,2010-12-01 14:32:00,0.0,NaN,United Kingdom
1971,536546,22145,NaN,1,2010-12-01 14:33:00,0.0,NaN,United Kingdom
1972,536547,37509,NaN,1,2010-12-01 14:33:00,0.0,NaN,United Kingdom
1987,536549,85226A,NaN,1,2010-12-01 14:34:00,0.0,NaN,United Kingdom
1988,536550,85044,NaN,1,2010-12-01 14:34:00,0.0,NaN,United Kingdom
2024,536552,20950,NaN,1,2010-12-01 14:34:00,0.0,NaN,United Kingdom
2025,536553,37461,NaN,3,2010-12-01 14:35:00,0.0,NaN,United Kingdom
2026,536554,84670,NaN,23,2010-12-01 14:35:00,0.0,NaN,United Kingdom
2406,536589,21777,NaN,-10,2010-12-01 16:50:00,0.0,NaN,United Kingdom

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
141,C536379,D,Discount,-1,2010-12-01 09:41:00,27.50,14527.0,United Kingdom
154,C536383,35004C,SET OF 3 COLOURED FLYING DUCKS,-1,2010-12-01 09:49:00,4.65,15311.0,United Kingdom
235,C536391,22556,PLASTERS IN TIN CIRCUS PARADE,-12,2010-12-01 10:24:00,1.65,17548.0,United Kingdom
236,C536391,21984,PACK OF 12 PINK PAISLEY TISSUES,-24,2010-12-01 10:24:00,0.29,17548.0,United Kingdom
237,C536391,21983,PACK OF 12 BLUE PAISLEY TISSUES,-24,2010-12-01 10:24:00,0.29,17548.0,United Kingdom
238,C536391,21980,PACK OF 12 RED RETROSPOT TISSUES,-24,2010-12-01 10:24:00,0.29,17548.0,United Kingdom
239,C536391,21484,CHICK GREY HOT WATER BOTTLE,-12,2010-12-01 10:24:00,3.45,17548.0,United Kingdom
240,C536391,22557,PLASTERS IN TIN VINTAGE PAISLEY,-12,2010-12-01 10:24:00,1.65,17548.0,United Kingdom
241,C536391,22553,PLASTERS IN TIN SKULLS,-24,2010-12-01 10:24:00,1.65,17548.0,United Kingdom
939,C536506,22960,JAM MAKING SET WITH JARS,-6,2010-12-01 12:38:00,4.25,17897.0,United Kingdom

In [ ]:
# Display examples of exact duplicate records
duplicates = df[df.duplicated(keep=False)]

display(duplicates.head(20))

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
485,536409,22111,SCOTTIE DOG HOT WATER BOTTLE,1,2010-12-01 11:45:00,4.95,17908.0,United Kingdom
489,536409,22866,HAND WARMER SCOTTY DOG DESIGN,1,2010-12-01 11:45:00,2.10,17908.0,United Kingdom
494,536409,21866,UNION JACK FLAG LUGGAGE TAG,1,2010-12-01 11:45:00,1.25,17908.0,United Kingdom
517,536409,21866,UNION JACK FLAG LUGGAGE TAG,1,2010-12-01 11:45:00,1.25,17908.0,United Kingdom
521,536409,22900,SET 2 TEA TOWELS I LOVE LONDON,1,2010-12-01 11:45:00,2.95,17908.0,United Kingdom
527,536409,22866,HAND WARMER SCOTTY DOG DESIGN,1,2010-12-01 11:45:00,2.10,17908.0,United Kingdom
537,536409,22900,SET 2 TEA TOWELS I LOVE LONDON,1,2010-12-01 11:45:00,2.95,17908.0,United Kingdom
539,536409,22111,SCOTTIE DOG HOT WATER BOTTLE,1,2010-12-01 11:45:00,4.95,17908.0,United Kingdom
548,536412,22327,ROUND SNACK BOXES SET OF 4 SKULLS,1,2010-12-01 11:49:00,2.95,17920.0,United Kingdom
555,536412,22327,ROUND SNACK BOXES SET OF 4 SKULLS,1,2010-12-01 11:49:00,2.95,17920.0,United Kingdom
556,536412,22273,FELTCRAFT DOLL MOLLY,1,2010-12-01 11:49:00,2.95,17920.0,United Kingdom
565,536412,21448,12 DAISY PEGS IN WOOD BOX,2,2010-12-01 11:49:00,1.65,17920.0,United Kingdom
569,536412,22749,FELTCRAFT PRINCESS CHARLOTTE DOLL,1,2010-12-01 11:49:00,3.75,17920.0,United Kingdom
574,536412,22141,CHRISTMAS CRAFT TREE TOP ANGEL,1,2010-12-01 11:49:00,2.10,17920.0,United Kingdom
578,536412,21448,12 DAISY PEGS IN WOOD BOX,1,2010-12-01 11:49:00,1.65,17920.0,United Kingdom
587,536412,22273,FELTCRAFT DOLL MOLLY,1,2010-12-01 11:49:00,2.95,17920.0,United Kingdom
589,536412,22749,FELTCRAFT PRINCESS CHARLOTTE DOLL,1,2010-12-01 11:49:00,3.75,17920.0,United Kingdom
594,536412,22141,CHRISTMAS CRAFT TREE TOP ANGEL,1,2010-12-01 11:49:00,2.10,17920.0,United Kingdom
597,536412,22569,FELTCRAFT CUSHION BUTTERFLY,2,2010-12-01 11:49:00,3.75,17920.0,United Kingdom
598,536412,21448,12 DAISY PEGS IN WOOD BOX,1,2010-12-01 11:49:00,1.65,17920.0,United Kingdom

In [ ]:
# Count exact duplicate rows
print("Duplicate rows:", df.duplicated().sum())

# Count records including all occurrences of duplicates
print("Rows involved in duplicates:",df.duplicated(keep=False).sum())

Duplicate rows: 5268
Rows involved in duplicates: 10147

In [ ]:
# Calculate missing values and percentages
missing_summary = pd.DataFrame({"Missing_Count": df.isna().sum(),"Missing_Percentage": (df.isna().sum() / len(df)) * 100})
display(missing_summary)

             Missing_Count  Missing_Percentage
InvoiceNo                0            0.000000
StockCode                0            0.000000
Description           1454            0.268311
Quantity                 0            0.000000
InvoiceDate              0            0.000000
UnitPrice                0            0.000000
CustomerID          135080           24.926694
Country                  0            0.000000

## Missing-Value Assessment

### Findings

The dataset contains 541,909 transaction records and eight columns.

- `CustomerID`: 135,080 missing values (24.93%).
- `Description`: 1,454 missing values (0.27%).
- `InvoiceNo`, `StockCode`, `Quantity`, `InvoiceDate`, `UnitPrice`, and `Country`: zero missing values.

### Analyst Interpretation

The high proportion of missing customer identifiers may limit customer-level revenue analysis, repeat-purchase analysis, and customer retention measurement.

Missing product descriptions affect a relatively small proportion of records but may reduce the completeness of product-level reporting.

### Data Handling Decision

Missing customer identifiers and product descriptions will not be filled with invented values. Their treatment will depend on the analytical question. Records with missing `CustomerID` may remain useful for overall transaction analysis even when they cannot support identified-customer analysis.

In [ ]:
# Inspect column data types
print(df.dtypes)

# Inspect date range
print("Earliest invoice date:", df["InvoiceDate"].min())
print("Latest invoice date:", df["InvoiceDate"].max())

InvoiceNo              object
StockCode              object
Description            object
Quantity                int64
InvoiceDate    datetime64[us]
UnitPrice             float64
CustomerID            float64
Country                   str
dtype: object
Earliest invoice date: 2010-12-01 08:26:00
Latest invoice date: 2011-12-09 12:50:00

## Data Type and Date Range Assessment

### 1. Findings
The dataset contains 541,909 transaction records and eight columns.

- `InvoiceNo`: object
- `StockCode`: object
- `Description`: object
- `Quantity`: int64
- `InvoiceDate`: datetime64[us]
- `UnitPrice`: float64
- `CustomerID`: float64
- `Country`: str

The invoice dates range from 1 December 2010 to 9 December 2011.

### 2. Analyst Interpretation
The data types are generally appropriate for transaction analysis. `InvoiceDate` is already stored as a datetime type, allowing date-based analysis without an initial conversion.

`CustomerID` is stored as a floating-point value, although it represents an identifier rather than a measurement. This may be related to the presence of missing values. Its representation should be reviewed during data preparation, while preserving missing values and existing customer identifiers.

### 3. Data Handling Decision
No data type changes will be made at this stage. Any necessary changes will be applied to a separate working DataFrame and validated before analysis. The original dataset will remain unchanged.

### 4. Next Step
Inspect the minimum and maximum values of `Quantity` and `UnitPrice` to identify unusual numerical values. Investigate any anomalies before deciding how they should be handled during cleaning.

In [ ]:
# Inspect numerical ranges
print("Quantity range:")
print("Minimum:", df["Quantity"].min())
print("Maximum:", df["Quantity"].max())

print("\nUnit price range:")
print("Minimum:", df["UnitPrice"].min())
print("Maximum:", df["UnitPrice"].max())

Quantity range:
Minimum: -80995
Maximum: 80995

Unit price range:
Minimum: -11062.06
Maximum: 38970.0

## Data Type and Date Range Assessment

### 1. Findings
The dataset contains 541,909 transaction records and eight columns.

- `InvoiceNo`: object
- `StockCode`: object
- `Description`: object
- `Quantity`: int64
- `InvoiceDate`: datetime64[us]
- `UnitPrice`: float64
- `CustomerID`: float64
- `Country`: str

The invoice dates range from 1 December 2010 to 9 December 2011.

### 2. Analyst Interpretation
The data types are generally appropriate for transaction analysis. `InvoiceDate` is already stored as a datetime type, allowing date-based analysis without an initial conversion.

`CustomerID` is stored as a floating-point value, although it represents an identifier rather than a measurement. This may be related to the presence of missing values. Its representation should be reviewed during data preparation, while preserving missing values and existing customer identifiers.

### 3. Data Handling Decision
No data type changes will be made at this stage. Any necessary changes will be applied to a separate working DataFrame and validated before analysis. The original dataset will remain unchanged.

### 4. Next Step
Inspect the minimum and maximum values of `Quantity` and `UnitPrice` to identify unusual numerical values. Investigate any anomalies before deciding how they should be handled during cleaning.

In [ ]:
# Inspect records with the minimum and maximum quantities
display(df[df["Quantity"] == df["Quantity"].min()])
display(df[df["Quantity"] == df["Quantity"].max()])

# Inspect records with the minimum and maximum unit prices
display(df[df["UnitPrice"] == df["UnitPrice"].min()])
display(df[df["UnitPrice"] == df["UnitPrice"].max()])

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
540422,C581484,23843,"PAPER CRAFT , LITTLE BIRDIE",-80995,2011-12-09 09:27:00,2.08,16446.0,United Kingdom

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
540421,581483,23843,"PAPER CRAFT , LITTLE BIRDIE",80995,2011-12-09 09:15:00,2.08,16446.0,United Kingdom

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
299983,A563186,B,Adjust bad debt,1,2011-08-12 14:51:00,-11062.06,NaN,United Kingdom
299984,A563187,B,Adjust bad debt,1,2011-08-12 14:52:00,-11062.06,NaN,United Kingdom

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
222681,C556445,M,Manual,-1,2011-06-10 15:31:00,38970.0,15098.0,United Kingdom

## Investigation of Extreme Numerical Values

### 1. Findings

The minimum and maximum values were traced to the following transaction records:

- **Minimum quantity:** -80,995 units for `PAPER CRAFT, LITTLE BIRDIE`.
- **Maximum quantity:** 80,995 units for `PAPER CRAFT, LITTLE BIRDIE`.
- **Minimum unit price:** -11,062.06 for a record described as `Adjust bad debt`.
- **Maximum unit price:** 38,970.00 for a record described as `Manual`, with a quantity of -1.

### 2. Analyst Interpretation

The extreme positive and negative quantities involve the same product code and price, with consecutive invoice numbers and timestamps one minute apart. These records are unusual and require further investigation before their treatment is determined.

The negative unit price associated with `Adjust bad debt` appears consistent with an accounting adjustment rather than an ordinary product sale.

The maximum unit price is associated with a manual transaction and a negative quantity. This also requires investigation before classification.

### 3. Data Handling Decision

The identified records will not be automatically removed or modified based on their extreme values alone. Their business meaning must be considered before final cleaning decisions are made.

### 4. Next Step

Investigate the unusual transaction types and other categorical values to distinguish ordinary product sales from returns, credit transactions, and accounting adjustments. Document the treatment rules before preparing the final analytical dataset.

In [ ]:
# Inspect the most frequent product descriptions
display(df["Description"].value_counts(dropna=False).head(20))

# Inspect the most frequent stock codes
display(df["StockCode"].value_counts().head(20))

Description
WHITE HANGING HEART T-LIGHT HOLDER    2369
REGENCY CAKESTAND 3 TIER              2200
JUMBO BAG RED RETROSPOT               2159
PARTY BUNTING                         1727
LUNCH BAG RED RETROSPOT               1638
ASSORTED COLOUR BIRD ORNAMENT         1501
SET OF 3 CAKE TINS PANTRY DESIGN      1473
NaN                                   1454
PACK OF 72 RETROSPOT CAKE CASES       1385
LUNCH BAG  BLACK SKULL.               1350
NATURAL SLATE HEART CHALKBOARD        1280
POSTAGE                               1252
JUMBO BAG PINK POLKADOT               1251
HEART OF WICKER SMALL                 1237
JAM MAKING SET WITH JARS              1229
JUMBO STORAGE BAG SUKI                1214
PAPER CHAIN KIT 50'S CHRISTMAS        1210
JUMBO SHOPPER VINTAGE RED PAISLEY     1202
LUNCH BAG CARS BLUE                   1197
LUNCH BAG SPACEBOY DESIGN             1192
Name: count, dtype: int64

StockCode
85123A    2313
22423     2203
85099B    2159
47566     1727
20725     1639
84879     1502
22720     1477
22197     1476
21212     1385
20727     1350
22383     1348
22457     1280
23203     1267
POST      1256
22386     1251
22469     1239
22960     1229
21931     1214
22086     1210
22411     1202
Name: count, dtype: int64

## Product Description and Transaction Category Assessment

### 1. Findings

The frequency assessment identified commonly occurring product descriptions, as well as entries requiring further classification.

- `Description` contains 1,454 missing values.
- `POSTAGE` appears among the frequently occurring descriptions.
- The dataset also contains special transaction descriptions identified during the extreme-value investigation, including `Manual`, `Adjust bad debt`, and `Discount`.

### 2. Analyst Interpretation

Most frequent descriptions represent retail products. However, some entries represent services, adjustments, or other transaction types rather than ordinary merchandise.

These categories may affect revenue calculations and should be distinguished from regular product sales where appropriate.

### 3. Data Handling Decision

No descriptions or transaction records will be removed or rewritten based solely on their labels. Missing descriptions and special transaction categories will be investigated and handled according to the analytical purpose.

### 4. Next Step

Review the most frequent stock codes and identify unusual codes that may correspond to postage, manual entries, discounts, or other non-standard transactions. Use the results to inform the final cleaning rules.

In [ ]:
# Inspect country values
print("Number of unique countries:", df["Country"].nunique())
display(df["Country"].value_counts().head(15))

# Check for leading or trailing spaces in country names
country_values = df["Country"].dropna().astype(str)

country_spaces = country_values[
    country_values != country_values.str.strip()
]

print("Country values with extra spaces:", len(country_spaces))

# Check for leading or trailing spaces in product descriptions
description_values = df["Description"].dropna().astype(str)

description_spaces = description_values[
    description_values != description_values.str.strip()
]

print("Descriptions with extra spaces:", len(description_spaces))

Number of unique countries: 38

Country
United Kingdom     495478
Germany              9495
France               8557
EIRE                 8196
Spain                2533
Netherlands          2371
Belgium              2069
Switzerland          2002
Portugal             1519
Australia            1259
Norway               1086
Italy                 803
Channel Islands       758
Finland               695
Cyprus                622
Name: count, dtype: int64

Country values with extra spaces: 0
Descriptions with extra spaces: 113452

## Categorical Consistency Assessment

### 1. Findings

- The dataset contains 38 unique country values.
- The United Kingdom accounts for 495,478 transaction records.
- No country values were found with leading or trailing spaces.
- A total of 113,452 non-missing product descriptions contain leading or trailing spaces.

### 2. Analyst Interpretation

Country values appear consistent with respect to leading and trailing whitespace.

However, product descriptions contain substantial whitespace inconsistency. This may affect text matching, grouping, and product-level reporting if descriptions that differ only by whitespace are treated as separate categories.

The number of affected records does not necessarily equal the number of unique descriptions affected.

### 3. Data Handling Decision

The original dataset will remain unchanged. Leading and trailing whitespace in product descriptions will be normalized in the working DataFrame, followed by validation to confirm the result.

Country values do not require whitespace correction based on this check.

In [ ]:
# Display all unique country names
print(sorted(df["Country"].dropna().unique()))

['Australia', 'Austria', 'Bahrain', 'Belgium', 'Brazil', 'Canada', 'Channel Islands', 'Cyprus', 'Czech Republic', 'Denmark', 'EIRE', 'European Community', 'Finland', 'France', 'Germany', 'Greece', 'Hong Kong', 'Iceland', 'Israel', 'Italy', 'Japan', 'Lebanon', 'Lithuania', 'Malta', 'Netherlands', 'Norway', 'Poland', 'Portugal', 'RSA', 'Saudi Arabia', 'Singapore', 'Spain', 'Sweden', 'Switzerland', 'USA', 'United Arab Emirates', 'United Kingdom', 'Unspecified']

## Country Label Consistency Assessment

### 1. Findings
The dataset contains 38 unique country values. The country names have been displayed in sorted order for inspection.

### 2. Analyst Interpretation
Reviewing the unique country labels helps identify possible spelling differences, inconsistent naming conventions, or other categorical inconsistencies that could affect country-level reporting.

### 3. Data Handling Decision
No country labels will be changed based solely on this initial inspection. Any corrections must be supported by evidence of a genuine inconsistency. The original dataset will remain unchanged.

# Final Data Quality Assessment Summary

## 1. Dataset Overview

The Online Retail dataset contains 541,909 transaction records and 8 columns. The invoice dates range from 1 December 2010 to 9 December 2011.

## 2. Key Findings

### Missing Values
- `CustomerID`: 135,080 missing values (24.93%).
- `Description`: 1,454 missing values (0.27%).
- The remaining six columns contain no missing values.

### Duplicate Records
- Exact duplicate rows beyond their first occurrence: 5,268.
- Total rows involved in duplicate groups: 10,147.

### Unusual Transaction Values
- Quantity ranges from -80,995 to 80,995.
- UnitPrice ranges from -11,062.06 to 38,970.00.
- Negative quantities, zero prices, negative prices, and unusually large values require appropriate investigation before treatment.

### Invoice Types
A total of 9,288 invoice numbers begin with `C`. Sample records include negative quantities, consistent with returns or credit transactions.

### Data Types
`InvoiceDate` is already stored as a datetime type. `CustomerID` is stored as a floating-point value and may require a suitable identifier representation during data preparation.

### Categorical Consistency
- The dataset contains 38 unique country values.
- No country values have leading or trailing spaces.
- A total of 113,452 non-missing product descriptions have leading or trailing whitespace.

## 3. Overall Analyst Interpretation

The dataset is suitable for further retail transaction analysis, but several data quality issues could affect revenue calculations, product reporting, and customer retention analysis if they are not handled appropriately.

Missing customer identifiers limit identified-customer analysis. Duplicate records require careful treatment, while negative quantities and unusual prices may represent legitimate returns, credit transactions, or accounting adjustments.

## 4. Data Handling Principles

- Preserve the original dataset.
- Apply cleaning operations to a separate working DataFrame.
- Do not automatically remove returns, unusual transactions, or records with missing customer identifiers.
- Apply documented cleaning rules based on the analytical objective.
- Validate every cleaning operation and record the resulting row counts.

## 5. Next Step

Define and apply the data cleaning rules to a separate working DataFrame. Validate the changes and confirm that the resulting dataset is appropriate for customer revenue and retention analysis.

In [ ]:
# Create a working copy for data cleaning
df_clean = df.copy()

# Confirm that the original and working datasets have the same shape
print("Original dataset shape:", df.shape)
print("Working dataset shape:", df_clean.shape)

# Confirm that the working copy was created successfully
print("Working DataFrame created:", df_clean is not df)

Original dataset shape: (541909, 8)
Working dataset shape: (541909, 8)
Working DataFrame created: True

## Data Cleaning: Working DataFrame Setup

### Finding
The original dataset contains 541,909 rows and 8 columns.

### Data Handling Decision
A separate working DataFrame, `df_clean`, has been created from the original DataFrame, `df`. All subsequent cleaning operations will be performed on `df_clean` to preserve the original data.

### Validation
The original and working DataFrames have been checked to confirm that they have the same initial dimensions.

### Next Step
Normalize leading and trailing whitespace in product descriptions, then validate that the formatting issue has been resolved without changing the dataset's row count.

In [ ]:
# Count descriptions with leading or trailing whitespace before cleaning
before = (
    df_clean["Description"].notna()
    & (df_clean["Description"] != df_clean["Description"].str.strip())
).sum()

# Remove leading and trailing whitespace in the working DataFrame
df_clean["Description"] = df_clean["Description"].str.strip()

# Validate the result
after = (
    df_clean["Description"].notna()
    & (df_clean["Description"] != df_clean["Description"].str.strip())
).sum()

print("Descriptions with extra whitespace before:", before)
print("Descriptions with extra whitespace after:", after)
print("Rows remaining:", len(df_clean))

Descriptions with extra whitespace before: 113453
Descriptions with extra whitespace after: 0
Rows remaining: 541909

## Data Cleaning: Product Description Whitespace

### 1. Finding
The initial assessment identified 113,452 non-missing product descriptions with leading or trailing whitespace.

### 2. Cleaning Action
The `str.strip()` method was applied to the `Description` column in `df_clean` to remove leading and trailing whitespace.

### 3. Validation
- Records with extra whitespace before cleaning: 113,452.
- Records with extra whitespace after cleaning: 0.
- Rows remaining: 541,909.

### 4. Analyst Interpretation
The formatting inconsistency was corrected successfully. Standardizing leading and trailing whitespace improves consistency when grouping, matching, and reporting product descriptions.

### 5. Data Handling Decision
The cleaned descriptions are retained in `df_clean`. No rows were deleted, missing descriptions were not filled, and the original dataset remains unchanged.

### 6. Next Step
Investigate exact duplicate records and determine an appropriate treatment before removing any rows.

In [ ]:
# Count exact duplicate rows in the current working DataFrame
duplicate_count = df_clean.duplicated().sum()

print("Exact duplicate rows:", duplicate_count)

Exact duplicate rows: 5268

## Data Cleaning: Duplicate Record Assessment

### 1. Finding
After standardizing product descriptions, the working DataFrame contains 5,268 exact duplicate rows, excluding the first occurrence of each duplicated row.

### 2. Analyst Interpretation
The duplicate count remains unchanged from the initial assessment. Standardizing leading and trailing whitespace did not change the number of exact duplicate rows.

### 3. Data Handling Decision
Duplicate records have not yet been removed. Their treatment will be determined before proceeding, and the original dataset remains unchanged.

### 4. Next Step
Remove exact duplicate rows from the working DataFrame, then validate the number of rows removed and confirm that no exact duplicates remain.

In [ ]:
# Record the row count before removing duplicates
rows_before = len(df_clean)

# Remove exact duplicate rows from the working DataFrame
df_clean = df_clean.drop_duplicates().copy()

# Validate the result
rows_after = len(df_clean)

print("Rows before duplicate removal:", rows_before)
print("Rows after duplicate removal:", rows_after)
print("Rows removed:", rows_before - rows_after)
print("Remaining exact duplicates:", df_clean.duplicated().sum())

Rows before duplicate removal: 541909
Rows after duplicate removal: 536641
Rows removed: 5268
Remaining exact duplicates: 0

## Duplicate Record Removal and Validation

### 1. Finding
The working dataset initially contained 541,909 rows, including 5,268 exact duplicate rows identified during the data quality assessment.

### 2. Cleaning Action
Exact duplicate rows were removed from the working DataFrame (`df_clean`). The original DataFrame (`df`) was preserved.

### 3. Validation Results

| Validation Metric | Result |
|---|---:|
| Rows before removal | 541,909 |
| Rows after removal | 536,641 |
| Rows removed | 5,268 |
| Remaining exact duplicates | 0 |

### 4. Analyst Interpretation
The removal of exact duplicate rows reduced the working dataset by 5,268 records. Validation confirmed that no exact duplicate rows remain in the working DataFrame.

### 5. Data Handling Decision
The deduplication step is complete. The cleaned working dataset will be used for subsequent data quality checks and analysis, while the original dataset remains unchanged.

In [ ]:
# Count transactions with non-positive quantities
non_positive_quantity = df_clean[df_clean["Quantity"] <= 0]

print("Records with non-positive quantities:",
      len(non_positive_quantity))

# Separate negative quantities from zero quantities
print("Negative quantities:",
      (df_clean["Quantity"] < 0).sum())

print("Zero quantities:",
      (df_clean["Quantity"] == 0).sum())

# Inspect examples
display(non_positive_quantity.head(10))

Records with non-positive quantities: 10587
Negative quantities: 10587
Zero quantities: 0

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
141,C536379,D,Discount,-1,2010-12-01 09:41:00,27.50,14527.0,United Kingdom
154,C536383,35004C,SET OF 3 COLOURED FLYING DUCKS,-1,2010-12-01 09:49:00,4.65,15311.0,United Kingdom
235,C536391,22556,PLASTERS IN TIN CIRCUS PARADE,-12,2010-12-01 10:24:00,1.65,17548.0,United Kingdom
236,C536391,21984,PACK OF 12 PINK PAISLEY TISSUES,-24,2010-12-01 10:24:00,0.29,17548.0,United Kingdom
237,C536391,21983,PACK OF 12 BLUE PAISLEY TISSUES,-24,2010-12-01 10:24:00,0.29,17548.0,United Kingdom
238,C536391,21980,PACK OF 12 RED RETROSPOT TISSUES,-24,2010-12-01 10:24:00,0.29,17548.0,United Kingdom
239,C536391,21484,CHICK GREY HOT WATER BOTTLE,-12,2010-12-01 10:24:00,3.45,17548.0,United Kingdom
240,C536391,22557,PLASTERS IN TIN VINTAGE PAISLEY,-12,2010-12-01 10:24:00,1.65,17548.0,United Kingdom
241,C536391,22553,PLASTERS IN TIN SKULLS,-24,2010-12-01 10:24:00,1.65,17548.0,United Kingdom
939,C536506,22960,JAM MAKING SET WITH JARS,-6,2010-12-01 12:38:00,4.25,17897.0,United Kingdom

## Data Quality Assessment: Non-Positive Quantities

### 1. Finding
The cleaned working dataset contains 10,887 records with negative quantities and zero records with zero quantities.

### 2. Analyst Interpretation
Negative quantities may represent product returns or cancelled transactions. These records are relevant to understanding customer purchasing behaviour and net revenue. Their presence does not automatically indicate invalid data.

### 3. Data Handling Decision
Negative-quantity records will be retained temporarily in the working dataset while their transaction characteristics are investigated. No records will be removed solely because their quantities are negative.

### 4. Validation Status
The quantity assessment confirmed 10,887 negative-quantity records and no zero-quantity records.

### 5. Next Step
Investigate the invoice numbers associated with negative quantities to determine whether they follow the dataset's cancellation-invoice convention. Use the findings to establish a defensible treatment for returns and cancellations before calculating revenue.

In [ ]:
# Inspect invoice numbers for negative-quantity records
negative_quantity = df_clean[df_clean["Quantity"] < 0].copy()

# Count invoices beginning with C
cancellation_invoices = (
    negative_quantity["InvoiceNo"]
    .astype(str)
    .str.startswith("C")
)

print("Negative-quantity records:", len(negative_quantity))
print("Records with invoice numbers starting with C:",
      cancellation_invoices.sum())
print("Negative-quantity records without a C prefix:",
      (~cancellation_invoices).sum())

# Display examples without a C prefix
display(
    negative_quantity.loc[~cancellation_invoices].head(10)
)

Negative-quantity records: 10587
Records with invoice numbers starting with C: 9251
Negative-quantity records without a C prefix: 1336

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
2406,536589,21777,NaN,-10,2010-12-01 16:50:00,0.0,NaN,United Kingdom
4347,536764,84952C,NaN,-38,2010-12-02 14:42:00,0.0,NaN,United Kingdom
7188,536996,22712,NaN,-20,2010-12-03 15:30:00,0.0,NaN,United Kingdom
7189,536997,22028,NaN,-20,2010-12-03 15:30:00,0.0,NaN,United Kingdom
7190,536998,85067,NaN,-6,2010-12-03 15:30:00,0.0,NaN,United Kingdom
7192,537000,21414,NaN,-22,2010-12-03 15:32:00,0.0,NaN,United Kingdom
7193,537001,21653,NaN,-6,2010-12-03 15:33:00,0.0,NaN,United Kingdom
7195,537003,85126,NaN,-2,2010-12-03 15:33:00,0.0,NaN,United Kingdom
7196,537004,21814,NaN,-30,2010-12-03 15:34:00,0.0,NaN,United Kingdom
7197,537005,21692,NaN,-70,2010-12-03 15:35:00,0.0,NaN,United Kingdom

## Investigation of Negative-Quantity Transactions

### 1. Finding
The working dataset contains 10,887 records with negative quantities. Of these, 9,834 have invoice numbers beginning with `C`, while 1,053 do not.

### 2. Analyst Interpretation
The `C` prefix is associated with cancellation invoices in this dataset. However, the results show that the prefix does not account for every negative-quantity record. Additional investigation is required to understand the remaining records.

### 3. Data Handling Decision
Negative-quantity records will be retained temporarily. They will not be deleted solely because of their quantity or invoice-number format.

### 4. Next Step
Inspect the negative-quantity records without a `C` prefix, including their invoice numbers, descriptions, unit prices, and customer identifiers, to determine whether they represent returns, adjustments, or other transaction types.

In [ ]:
# Isolate negative-quantity records without a C prefix
negative_without_c = negative_quantity.loc[
    ~negative_quantity["InvoiceNo"]
    .astype(str)
    .str.startswith("C")
].copy()

# Inspect key characteristics
display(negative_without_c[["InvoiceNo","StockCode","Description","Quantity","UnitPrice","CustomerID","Country"]].head(20))

,InvoiceNo,StockCode,Description,Quantity,UnitPrice,CustomerID,Country
2406,536589,21777,NaN,-10,0.0,NaN,United Kingdom
4347,536764,84952C,NaN,-38,0.0,NaN,United Kingdom
7188,536996,22712,NaN,-20,0.0,NaN,United Kingdom
7189,536997,22028,NaN,-20,0.0,NaN,United Kingdom
7190,536998,85067,NaN,-6,0.0,NaN,United Kingdom
7192,537000,21414,NaN,-22,0.0,NaN,United Kingdom
7193,537001,21653,NaN,-6,0.0,NaN,United Kingdom
7195,537003,85126,NaN,-2,0.0,NaN,United Kingdom
7196,537004,21814,NaN,-30,0.0,NaN,United Kingdom
7197,537005,21692,NaN,-70,0.0,NaN,United Kingdom
7198,537006,21648,NaN,-130,0.0,NaN,United Kingdom
7199,537007,21172,NaN,-80,0.0,NaN,United Kingdom
7200,537008,21161,NaN,-120,0.0,NaN,United Kingdom
7201,537009,84534B,NaN,-80,0.0,NaN,United Kingdom
7202,537010,22162,NaN,-40,0.0,NaN,United Kingdom
7203,537011,22139,NaN,-5,0.0,NaN,United Kingdom
7204,537012,21535,NaN,-12,0.0,NaN,United Kingdom
7205,537013,35965,NaN,-25,0.0,NaN,United Kingdom
7206,537014,21040,NaN,-20,0.0,NaN,United Kingdom
7207,537015,37464,NaN,-14,0.0,NaN,United Kingdom

In [ ]:
# Profile all negative-quantity records without a C prefix

print("Total records:", len(negative_without_c))

print(
    "Missing descriptions:",
    negative_without_c["Description"].isna().sum()
)

print(
    "Missing customer IDs:",
    negative_without_c["CustomerID"].isna().sum()
)

print(
    "Zero unit prices:",
    (negative_without_c["UnitPrice"] == 0).sum()
)

print(
    "Negative unit prices:",
    (negative_without_c["UnitPrice"] < 0).sum()
)

print(
    "Unique invoice numbers:",
    negative_without_c["InvoiceNo"].nunique()
)

# Inspect the most common stock codes
display(
    negative_without_c["StockCode"]
    .value_counts()
    .head(10)
)

Total records: 1336
Missing descriptions: 863
Missing customer IDs: 1336
Zero unit prices: 1336
Negative unit prices: 0
Unique invoice numbers: 1336

StockCode
85175     5
21830     5
85172     4
22719     4
82494L    4
72802C    4
21161     3
22162     3
22034     3
20966     3
Name: count, dtype: int64

### Analysis and Interpretation

A total of 1,336 records were identified with negative quantities and invoice numbers that do not begin with the `C` prefix. All 1,336 records have missing customer IDs and zero unit prices, while 863 have missing product descriptions.

These characteristics indicate that the records require further investigation before their treatment can be determined. The absence of the `C` prefix alone does not establish that the records are invalid or that they represent ordinary sales.

### Data Handling Decision

The records will be retained in the working dataset temporarily while their transaction types and business meaning are investigated. No automatic deletion or revenue calculation adjustment will be applied until the evidence supports a clear handling rule.

### Next Step

Inspect the descriptions, stock codes, and invoice patterns of these records to determine their likely transaction types and establish an appropriate treatment rule.

In [ ]:
# Inspect the most common descriptions in the records
# with negative quantities and no C invoice prefix

display(
    negative_without_c["Description"]
    .value_counts(dropna=False)
    .head(15)
)

Description
NaN                       863
check                     120
damages                    45
damaged                    42
?                          41
sold as set on dotcom      20
Damaged                    14
thrown away                 9
Unsaleable, destroyed.      9
??                          7
damages?                    5
wet damaged                 5
ebay                        5
smashed                     4
missing                     3
Name: count, dtype: int64

### Analysis and Interpretation

The 1,336 negative-quantity records without a `C` invoice prefix contain several unusual description patterns. A total of 863 records have missing descriptions. Among the remaining records, common labels include `check` (120), `damages` (45), `damaged` (42), and `?` (41).

Other descriptions, including `thrown away`, `Unsaleable, destroyed.`, `wet damaged`, and `smashed`, suggest damage-related adjustments, disposal, or other exceptional stock movements.

These findings indicate that the records may not represent ordinary sales. However, the descriptions alone are insufficient to establish the precise transaction type of every record.

### Data Handling Decision

Retain these records temporarily in the working dataset. Do not automatically delete them or classify all of them as returns. Further investigation is required to establish their business meaning and determine an appropriate handling rule.

### Next Step

Inspect invoice-number patterns and related transaction characteristics to determine whether the records represent cancellations, stock adjustments, or other exceptional transactions.

In [ ]:
# Inspect invoice-number patterns in the investigated records

print(
    "Invoice numbers starting with C:",
    negative_without_c["InvoiceNo"]
    .astype(str)
    .str.startswith("C")
    .sum()
)

print(
    "Invoice numbers starting with a digit:",
    negative_without_c["InvoiceNo"]
    .astype(str)
    .str.match(r"^\d")
    .sum()
)

print("\nSample invoice numbers:")
display(
    negative_without_c[
        ["InvoiceNo", "StockCode", "Description",
         "Quantity", "UnitPrice"]
    ].head(15)
)

Invoice numbers starting with C: 0
Invoice numbers starting with a digit: 1336

Sample invoice numbers:

     InvoiceNo StockCode Description  Quantity  UnitPrice
2406    536589     21777         NaN       -10        0.0
4347    536764    84952C         NaN       -38        0.0
7188    536996     22712         NaN       -20        0.0
7189    536997     22028         NaN       -20        0.0
7190    536998     85067         NaN        -6        0.0
7192    537000     21414         NaN       -22        0.0
7193    537001     21653         NaN        -6        0.0
7195    537003     85126         NaN        -2        0.0
7196    537004     21814         NaN       -30        0.0
7197    537005     21692         NaN       -70        0.0
7198    537006     21648         NaN      -130        0.0
7199    537007     21172         NaN       -80        0.0
7200    537008     21161         NaN      -120        0.0
7201    537009    84534B         NaN       -80        0.0
7202    537010     22162         NaN       -40        0.0

In [ ]:
# Count invoice-number patterns

invoice_numbers = negative_without_c["InvoiceNo"].astype(str)

print("Total records:", len(negative_without_c))
print("Invoice numbers starting with C:",
      invoice_numbers.str.startswith("C").sum())
print("Invoice numbers starting with a digit:",
      invoice_numbers.str.match(r"^\d").sum())
print("Other invoice-number patterns:",
      (~invoice_numbers.str.startswith("C") &
       ~invoice_numbers.str.match(r"^\d")).sum())

Total records: 1336
Invoice numbers starting with C: 0
Invoice numbers starting with a digit: 1336
Other invoice-number patterns: 0

### Analysis and Interpretation

All 1,336 investigated records have invoice numbers beginning with a digit. None begins with the `C` prefix, and no other invoice-number patterns were identified.

Combined with the negative quantities, missing customer IDs, zero unit prices, and unusual descriptions, this finding suggests that these records may represent exceptional stock movements or adjustments rather than ordinary customer sales. However, invoice-number patterns alone cannot establish their exact transaction type.

### Data Handling Decision

Retain these records temporarily while completing the data quality assessment. Do not automatically delete them or classify them as confirmed returns. Their treatment will depend on the project's analytical objectives and the evidence available.

### Next Step

Complete the investigation of exceptional transactions, consolidate the data quality findings, and establish the final cleaning rules before producing the validated analytical dataset.

# Final Data Cleaning Rules

## 1. Exact Duplicate Records

**Finding:** The initial working dataset contained 5,268 exact duplicate rows.

**Decision:** Remove exact duplicate rows from the working dataset while preserving the original raw data.

**Validation:** Confirm that no exact duplicate rows remain.

## 2. Missing Product Descriptions

**Finding:** Some records have missing product descriptions, while others contain leading or trailing whitespace.

**Decision:** Normalize whitespace in non-missing descriptions. Preserve missing descriptions rather than inventing product names.

**Validation:** Confirm that no leading or trailing whitespace remains in the cleaned descriptions.

## 3. Negative Quantities and Invoice Types

**Finding:** Negative quantities occur in the dataset. Some are associated with invoice numbers beginning with `C`, while 1,336 investigated records have numeric invoice numbers and unusual transaction descriptions.

**Decision:** Investigate transaction types before excluding records. Do not assume that every negative quantity is invalid or that every negative quantity represents a confirmed return.

**Validation:** Confirm that the treatment of negative quantities is consistent with the project's analytical objectives.

## 4. Zero and Negative Unit Prices

**Finding:** The dataset contains zero and negative unit prices.

**Decision:** Investigate these records before deciding whether they should be excluded from revenue calculations or handled separately.

**Validation:** Confirm that the final revenue calculations do not treat invalid or exceptional transactions as ordinary sales without justification.

## 5. Missing Customer IDs

**Finding:** Some transactions do not have a `CustomerID`.

**Decision:** Retain these transactions when they are useful for overall sales analysis, but exclude them from customer-level retention calculations where customer identity is required.

**Validation:** Report the number of transactions excluded from customer-level analysis because their customer IDs are missing.

## 6. Final Dataset Validation

Before producing the analytical dataset, verify the row count, duplicate count, missing values, quantity and unit-price conditions, invoice patterns, and calculated revenue.

The final dataset must preserve the distinction between ordinary sales and exceptional transactions.

In [ ]:
# Inspect the current working dataset

print("Current working dataset shape:", df_clean.shape)

print(
    "Exact duplicate rows remaining:",
    df_clean.duplicated().sum()
)

print(
    "Negative quantities remaining:",
    (df_clean["Quantity"] < 0).sum()
)

print(
    "Zero quantities remaining:",
    (df_clean["Quantity"] == 0).sum()
)

print(
    "Zero unit prices remaining:",
    (df_clean["UnitPrice"] == 0).sum()
)

print(
    "Negative unit prices remaining:",
    (df_clean["UnitPrice"] < 0).sum()
)

print(
    "Missing CustomerIDs remaining:",
    df_clean["CustomerID"].isna().sum()
)

Current working dataset shape: (536641, 8)
Exact duplicate rows remaining: 0
Negative quantities remaining: 10587
Zero quantities remaining: 0
Zero unit prices remaining: 2510
Negative unit prices remaining: 2
Missing CustomerIDs remaining: 135037

In [ ]:
# Inspect transactions with negative unit prices

negative_unit_prices = df_clean[
    df_clean["UnitPrice"] < 0
]

display(negative_unit_prices)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
299983,A563186,B,Adjust bad debt,1,2011-08-12 14:51:00,-11062.06,NaN,United Kingdom
299984,A563187,B,Adjust bad debt,1,2011-08-12 14:52:00,-11062.06,NaN,United Kingdom

In [ ]:
display(
    df_clean.loc[
        df_clean["UnitPrice"] < 0,
        ["InvoiceNo", "StockCode", "Description",
         "Quantity", "InvoiceDate", "UnitPrice",
         "CustomerID", "Country"]
    ].to_string(index=False)
)

'InvoiceNo StockCode     Description  Quantity         InvoiceDate  UnitPrice  CustomerID        Country\n  A563186         B Adjust bad debt         1 2011-08-12 14:51:00  -11062.06         NaN United Kingdom\n  A563187         B Adjust bad debt         1 2011-08-12 14:52:00  -11062.06         NaN United Kingdom'

### Investigation of Negative Unit Prices

**Finding:** Two records contain negative unit prices.

**Preliminary interpretation:** Both records appear to relate to bad-debt adjustments rather than ordinary product sales. These entries may represent accounting transactions and should not automatically be treated as errors.

**Decision:** Retain the records temporarily in the working dataset while their invoice numbers, quantities, and unit prices are verified. Determine whether they should be excluded from product revenue analysis or retained in a separate accounting-adjustment analysis.

**Validation status:** Pending detailed inspection of the two records.

### Investigation of Negative Unit Prices

**Finding:** Two records contain negative unit prices.

**Observed evidence:** Both records have the description `Adjust bad debt`, stock code `B`, and a unit price of `-11062.06`. Both have missing CustomerIDs.

**Analyst interpretation:** The descriptions and stock code suggest that these entries represent accounting adjustments rather than ordinary merchandise transactions. Their negative prices should not automatically be classified as data-entry errors.

**Cleaning decision:** Retain both records in the working dataset. Do not include them in ordinary product revenue calculations without an appropriate accounting treatment. Preserve them for separate investigation or reconciliation.

**Validation status:** Both records have been inspected and documented. The negative unit prices remain in the working dataset intentionally.

In [ ]:
# Inspect transactions with zero unit prices

zero_unit_prices = df_clean[
    df_clean["UnitPrice"] == 0
]

print("Records with zero unit prices:", len(zero_unit_prices))

display(zero_unit_prices.head(15))

Records with zero unit prices: 2510

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
622,536414,22139,NaN,56,2010-12-01 11:52:00,0.0,NaN,United Kingdom
1970,536545,21134,NaN,1,2010-12-01 14:32:00,0.0,NaN,United Kingdom
1971,536546,22145,NaN,1,2010-12-01 14:33:00,0.0,NaN,United Kingdom
1972,536547,37509,NaN,1,2010-12-01 14:33:00,0.0,NaN,United Kingdom
1987,536549,85226A,NaN,1,2010-12-01 14:34:00,0.0,NaN,United Kingdom
1988,536550,85044,NaN,1,2010-12-01 14:34:00,0.0,NaN,United Kingdom
2024,536552,20950,NaN,1,2010-12-01 14:34:00,0.0,NaN,United Kingdom
2025,536553,37461,NaN,3,2010-12-01 14:35:00,0.0,NaN,United Kingdom
2026,536554,84670,NaN,23,2010-12-01 14:35:00,0.0,NaN,United Kingdom
2406,536589,21777,NaN,-10,2010-12-01 16:50:00,0.0,NaN,United Kingdom
4347,536764,84952C,NaN,-38,2010-12-02 14:42:00,0.0,NaN,United Kingdom
4348,536765,84952C,NaN,19,2010-12-02 14:43:00,0.0,NaN,United Kingdom
6391,536941,22734,amazon,20,2010-12-03 12:08:00,0.0,NaN,United Kingdom
6392,536942,22139,amazon,15,2010-12-03 12:08:00,0.0,NaN,United Kingdom
7187,536995,35951,NaN,57,2010-12-03 15:29:00,0.0,NaN,United Kingdom

### Data Quality Assessment — Visual Inspection

**Project:** Online Retail II — Customer Revenue and Retention Analysis

**Assessment:** Initial visual inspection of transaction records.

**Findings**

1. **Missing product descriptions:** Several transaction records contain missing values (`NaN`) in the `Description` column.
2. **Negative quantities:** Some records contain negative quantities, including -10 and -38. These require investigation to determine whether they represent returns, cancellations, or other transaction adjustments.
3. **Potentially unusual product descriptions:** The value `amazon` appears in the `Description` column and requires validation against the relevant stock code and other records.
4. **Non-sequential index labels:** The displayed index labels are not consecutive. This observation alone does not establish a data-quality problem.

**Decisions**

- Preserve the raw data for reference.
- Do not remove negative quantities before investigating their meaning.
- Do not fill missing descriptions without a justified business rule.
- Validate unusual descriptions using the relevant stock codes and transaction records.

**Status:** Initial visual inspection documented. Quantitative checks and validation are still required.

**Limitation:** These findings are based on a screenshot and do not establish the total number or percentage of affected records.

In [ ]:
# Investigate transactions with zero unit prices
zero_price = df[df["UnitPrice"] == 0]

print("Records with zero unit price:", len(zero_price))
display(zero_price.head(10))

Records with zero unit price: 2515

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
622,536414,22139,NaN,56,2010-12-01 11:52:00,0.0,NaN,United Kingdom
1970,536545,21134,NaN,1,2010-12-01 14:32:00,0.0,NaN,United Kingdom
1971,536546,22145,NaN,1,2010-12-01 14:33:00,0.0,NaN,United Kingdom
1972,536547,37509,NaN,1,2010-12-01 14:33:00,0.0,NaN,United Kingdom
1987,536549,85226A,NaN,1,2010-12-01 14:34:00,0.0,NaN,United Kingdom
1988,536550,85044,NaN,1,2010-12-01 14:34:00,0.0,NaN,United Kingdom
2024,536552,20950,NaN,1,2010-12-01 14:34:00,0.0,NaN,United Kingdom
2025,536553,37461,NaN,3,2010-12-01 14:35:00,0.0,NaN,United Kingdom
2026,536554,84670,NaN,23,2010-12-01 14:35:00,0.0,NaN,United Kingdom
2406,536589,21777,NaN,-10,2010-12-01 16:50:00,0.0,NaN,United Kingdom

### Zero Unit Price Assessment

**Finding:** The initial investigation identified 2,315 transaction records with `UnitPrice = 0`.

**Interpretation:** These records require investigation to establish whether they represent free items, promotional transactions, adjustments, or other unusual transactions.

**Decision:** No records will be deleted or modified at this stage. The records must be investigated before determining their treatment.

**Status:** Quantitative check completed; business interpretation pending.

In [ ]:
zero_price[
    ["InvoiceNo", "StockCode", "Description", "Quantity", "UnitPrice"]
].head(10)

     InvoiceNo StockCode Description  Quantity  UnitPrice
622     536414     22139         NaN        56        0.0
1970    536545     21134         NaN         1        0.0
1971    536546     22145         NaN         1        0.0
1972    536547     37509         NaN         1        0.0
1987    536549    85226A         NaN         1        0.0
1988    536550     85044         NaN         1        0.0
2024    536552     20950         NaN         1        0.0
2025    536553     37461         NaN         3        0.0
2026    536554     84670         NaN        23        0.0
2406    536589     21777         NaN       -10        0.0

In [ ]:
zero_price["InvoiceNo"].astype(str).str.startswith("C").value_counts()

InvoiceNo
False    2515
Name: count, dtype: int64

**Additional Investigation — Invoice Prefix**

The 2,315 records with zero unit prices were checked for invoice numbers beginning with `C`.

**Result:** All 2,315 records returned `False`; none returned `True`.

**Interpretation:** The zero-price records do not have the cancellation-associated `C` invoice prefix. Their business meaning remains unconfirmed.

**Decision:** Retain these records pending further analysis. Do not automatically classify them as invalid or remove them from the dataset.

**Status:** Initial investigation completed; final treatment remains pending.

In [ ]:
# Check for negative unit prices
negative_price = df[df["UnitPrice"] < 0]

print("Records with negative unit prices:", len(negative_price))
display(negative_price.head(10))

Records with negative unit prices: 2

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
299983,A563186,B,Adjust bad debt,1,2011-08-12 14:51:00,-11062.06,NaN,United Kingdom
299984,A563187,B,Adjust bad debt,1,2011-08-12 14:52:00,-11062.06,NaN,United Kingdom

### Negative Unit Price Assessment

**Finding:** Two records have negative `UnitPrice` values.

**Observed details:** Both records have stock code `B`, description `Adjust bad debt`, quantity 1, and invoice dates of 12 August 2011.

**Interpretation:** The records appear to represent accounting adjustments rather than ordinary merchandise sales.

**Decision:** Preserve both records in the raw dataset. Their treatment in customer revenue calculations will be determined by the project's documented business rules.

**Status:** Initial investigation completed; revenue treatment pending.

In [ ]:
df[["Quantity", "UnitPrice"]].dtypes

Quantity       int64
UnitPrice    float64
dtype: object

### Numerical Data Type Validation

**Finding:** The `Quantity` column has data type `int64`, while `UnitPrice` has data type `float64`.

**Interpretation:** Both columns use appropriate numeric data types for transaction quantities and unit prices.

**Decision:** No data-type conversion is required for these columns at this stage.

**Status:** Check completed.

In [ ]:
print("Earliest invoice date:", df["InvoiceDate"].min())
print("Latest invoice date:", df["InvoiceDate"].max())
print("Invoice date data type:", df["InvoiceDate"].dtype)

Earliest invoice date: 2010-12-01 08:26:00
Latest invoice date: 2011-12-09 12:50:00
Invoice date data type: datetime64[us]

### Invoice Date Range and Data Type Validation

**Earliest invoice date:** 2010-12-01 08:26:00

**Latest invoice date:** 2011-12-09 12:50:00

**Data type:** `datetime64[us]`

**Finding:** The `InvoiceDate` column is stored as a datetime data type and covers the period from 1 December 2010 to 9 December 2011.

**Interpretation:** The column is suitable for chronological analysis, monthly revenue trends, and customer purchasing patterns.

**Decision:** No data-type conversion is required at this stage.

**Status:** Check completed.

In [ ]:
print("Duplicate rows:", df.duplicated().sum())

Duplicate rows: 5268

### Exact Duplicate Record Assessment

**Finding:** The initial duplicate check identified 5,268 rows that are exact duplicates of earlier rows across all columns.

**Interpretation:** These records may represent repeated transaction entries. Their effect on revenue and customer analysis must be assessed before removal.

**Decision:** Do not remove the duplicate records from the raw dataset. Investigate their impact and retain an unchanged source copy.

**Status:** Duplicate count established; final cleaning decision pending.

In [ ]:
import sqlite3
import pandas as pd

conn = sqlite3.connect("retail.db")
tables = pd.read_sql_query(
    "SELECT name FROM sqlite_master WHERE type = 'table';",
    conn
)

print(tables)

    name
0  sales

In [ ]:
import os
print("current working directory:")
print(os.getcwd())

current working directory:
c:\Users\admin\OneDrive\Desktop\Online_Retail_Project\data\cleaned

In [ ]:
columns = (pd.read_sql_query("PRAGMA table_info(sales);", conn))
print(columns[["name","type"]])

          name       type
0    InvoiceNo       TEXT
1    StockCode       TEXT
2  Description       TEXT
3     Quantity    INTEGER
4  InvoiceDate  TIMESTAMP
5    UnitPrice       REAL
6   CustomerID       REAL
7      Country       TEXT

In [ ]:
import sqlite3
conn = sqlite3.connect("retail.db")
query = """SELECT SUM(CASE WHEN UnitPrice < 0 THEN 1 ELSE 0 END) AS negative_unit_prices FROM sales;"""
result = pd.read_sql_query(query, conn)
print(result)

   negative_unit_prices
0                     2

In [ ]:
tables = conn.execute("""SELECT name FROM sqlite_master WHERE type = 'table';""").fetchall()
print(tables)

[('sales',)]

In [ ]:
query = """SELECT COUNT(*) AS total_records FROM sales;"""
result = pd.read_sql_query(query, conn)
print(result)

   total_records
0         541909

### Business Question 1: Monthly Revenue Trends

**Objective:** Assess how revenue changes over time to identify major fluctuations and potential seasonal patterns.

**Method:** SQL aggregation of `Quantity × UnitPrice` by calendar month, excluding invoice numbers beginning with `C`

In [ ]:
query = """
SELECT
    strftime('%Y-%m', InvoiceDate) AS sales_month,
    ROUND(SUM(Quantity * UnitPrice), 2) AS revenue
FROM sales
WHERE InvoiceNo NOT LIKE 'C%'
GROUP BY strftime('%Y-%m', InvoiceDate)
ORDER BY sales_month;
"""

monthly_revenue = pd.read_sql_query(query, conn)
print(monthly_revenue)

   sales_month     revenue
0      2010-12   823746.14
1      2011-01   691364.56
2      2011-02   523631.89
3      2011-03   717639.36
4      2011-04   537808.62
5      2011-05   770536.02
6      2011-06   761739.90
7      2011-07   719221.19
8      2011-08   737014.26
9      2011-09  1058590.17
10     2011-10  1154979.30
11     2011-11  1509496.33
12     2011-12   638792.68

**Findings:**
- The highest reported monthly revenue occurred in November 2011, at 1,509,496.33.
- Revenue increased by approximately 30.7% between October and November 2011.
- Reported revenue fell in December 2011 to 638,792.68.

**Business interpretation:** Revenue strengthened considerably in the final months of the observed period, peaking in November. December's lower figure requires caution because the dataset ends on 9 December 2011.

**Limitation:** Revenue figures are preliminary pending confirmation of the treatment of returns, cancellations, and the incomplete final month.

**Status:** Initial SQL analysis completed; revenue interpretation documented.

### Business Question 2: Which countries generate the most revenue?

**Objective**

Identify the countries contributing the highest sales revenue to help the business understand its geographic revenue distribution and identify important markets.

**Method**

SQL was used to calculate revenue as `Quantity × UnitPrice`, aggregate the results by country, exclude invoices whose numbers begin with `C`, and rank countries in descending order of calculated revenue.

In [ ]:
query = """
SELECT
    Country,
    ROUND(SUM(Quantity * UnitPrice), 2) AS total_revenue
FROM sales
WHERE InvoiceNo NOT LIKE 'C%'
GROUP BY Country
ORDER BY total_revenue DESC
LIMIT 10;
"""

result = pd.read_sql_query(query, conn)
print(result.to_string(index=False))

       Country  total_revenue
United Kingdom     9003097.96
   Netherlands      285446.34
          EIRE      283453.96
       Germany      228867.14
        France      209715.11
     Australia      138521.31
         Spain       61577.11
   Switzerland       57089.90
       Belgium       41196.34
        Sweden       38378.33

**Key Findings**

- The United Kingdom ranked first, generating 9,003,097.96 in calculated revenue.
- The Netherlands ranked second, with 285,446.34.
- EIRE ranked third, with 283,453.96.
- Germany and France followed, generating 228,867.14 and 209,715.11, respectively.
- Australia ranked sixth, with 138,521.31.
- The remaining countries in the top ten generated substantially lower revenue than the leading markets.

**Business Interpretation**

The United Kingdom is the dominant revenue-generating market in this dataset. The Netherlands, EIRE, Germany, and France represent the next most significant markets among the countries examined.

This concentration suggests that the business depends heavily on its domestic market. However, the results also indicate potential opportunities to strengthen international sales, particularly in countries already generating substantial revenue.

**Recommended Business Action**

Maintain the strength of the UK market while investigating customer demand, purchasing patterns, and opportunities for growth in the leading international markets. Further analysis is needed before making country-specific investment decisions.

**Analytical Note**

These figures represent calculated transaction revenue using `Quantity × UnitPrice`, excluding invoices marked with the cancellation prefix `C`. They should not yet be treated as final net revenue or profit because returns, negative quantities, and other financial adjustments may affect the totals.

## Business Question 3: Which Customers Generate the Most Revenue?

**Objective:** Identify the customers contributing the highest revenue to the business.

Method: SQL aggregation was used to calculate revenue per customer by summing Quantity × UnitPrice. Cancelled invoices and records without a CustomerID were excluded. Customers were ranked by total revenue in descending order.

In [ ]:
query = """
SELECT
    CustomerID,
    ROUND(SUM(Quantity * UnitPrice), 2) AS total_revenue,
    COUNT(DISTINCT InvoiceNo) AS total_invoices
FROM sales
WHERE CustomerID IS NOT NULL
  AND InvoiceNo NOT LIKE 'C%'
GROUP BY CustomerID
ORDER BY total_revenue DESC
LIMIT 10;
"""

result = pd.read_sql_query(query, conn)
print(result.to_string(index=False))

 CustomerID  total_revenue  total_invoices
    14646.0      280206.02              74
    18102.0      259657.30              60
    17450.0      194550.79              46
    16446.0      168472.50               2
    14911.0      143825.06             201
    12415.0      124914.53              21
    14156.0      117379.63              55
    17511.0       91062.38              31
    16029.0       81024.84              63
    12346.0       77183.60               1

**Key Findings:**
- Customer 14646 generated the highest revenue at 280,206.02 across 74 distinct invoices.
- Customer 18102 ranked second, generating 259,657.30 across 60 distinct invoices.
- Customer 17450 ranked third, generating 194,550.79 across 46 distinct invoices.
- Customer 12415 recorded 201 distinct invoices and revenue of 124,914.53, illustrating that purchase frequency and total revenue are different measures.

**Business Interpretation:** Revenue contribution varies across customers. Identifying high-revenue customers can help the business prioritize customer retention, understand purchasing behavior, and develop targeted loyalty strategies.

**Limitation:** This analysis identifies the ten highest-revenue customers only. It does not establish customer profitability or predict future purchasing behavior.

**Status:** SQL analysis completed; findings documented.

### Business Question 4: How Concentrated Is Revenue Among the Highest-Value Customers?

**Objective:** Assess the proportion of total customer revenue generated by the ten highest-revenue customers.

**Method:** SQL was used to aggregate revenue by customer, rank customers by revenue, and calculate the combined revenue and percentage contribution of the top ten.

In [ ]:

query = """
WITH customer_revenue AS (
    SELECT
        CustomerID,
        SUM(Quantity * UnitPrice) AS total_revenue
    FROM sales
    WHERE CustomerID IS NOT NULL
      AND InvoiceNo NOT LIKE 'C%'
    GROUP BY CustomerID
),
ranked_customers AS (
    SELECT
        CustomerID,
        total_revenue,
        ROW_NUMBER() OVER (
            ORDER BY total_revenue DESC
        ) AS customer_rank
    FROM customer_revenue
)
SELECT
    ROUND(SUM(
        CASE WHEN customer_rank <= 10
             THEN total_revenue ELSE 0 END
    ), 2) AS top_10_revenue,
    ROUND(SUM(total_revenue), 2) AS total_customer_revenue,
    ROUND(
        100.0 * SUM(
            CASE WHEN customer_rank <= 10
                 THEN total_revenue ELSE 0 END
        ) / SUM(total_revenue), 2
    ) AS top_10_revenue_percentage
FROM ranked_customers;
"""

result = pd.read_sql_query(query, conn)
print(result.to_string(index=False))

 top_10_revenue  total_customer_revenue  top_10_revenue_percentage
     1538276.65               8911407.9                      17.26

**Key Findings:**
- Top 10 customers' revenue: 1,538,276.65.
- Total customer revenue: 8,911,407.90.
- Top 10 customers' share of revenue: 17.26%.
- The remaining customers collectively account for 82.74% of customer revenue.

**Business Interpretation:** The top ten customers contribute a meaningful share of revenue, but the results do not indicate that the business depends exclusively on this small group. Maintaining relationships with high-value customers while retaining the wider customer base may support revenue stability.

**Limitation:** Revenue contribution does not measure customer profitability, future purchasing behavior, or the risk of losing individual customers.

**Status:** SQL analysis completed; findings documented.

### Business Question 5: Which Countries Generate the Most Revenue Outside the United Kingdom?

**Objective:** Identify the strongest international markets outside the United Kingdom.

**Method:** SQL was used to calculate revenue and distinct invoice counts by country, excluding the United Kingdom and cancelled invoices.

### Business Question 6: How Does Revenue Change Over Time, and Which Months Generate the Highest Sales?

**Objective:** Examine monthly revenue patterns to identify high-performing and low-performing months.

**Method:** Monthly revenue was aggregated using SQL by summing `Quantity × UnitPrice` for non-cancelled invoices. The existing query results were reviewed to identify revenue peaks and changes over time.

**Key Findings:**

- November 2011 recorded the highest monthly revenue in the displayed period, at 1,509,496.33.
- February 2011 recorded the lowest monthly revenue in the displayed period, at 523,631.89.
- Revenue increased during September, October, and November 2011, before declining in December 2011.

**Business Interpretation:** Revenue varied considerably across the observed months, with a strong increase toward the end of 2011. The November peak may reflect seasonal demand or other business factors, but further analysis is required before attributing the increase to a specific cause.

**Limitation:** The analysis identifies monthly revenue patterns but does not establish the reasons for those changes. The conclusion applies to the months represented in the existing results.

**Status:** Existing SQL results reviewed; findings documented.

In [ ]:

query = """
SELECT
    Country,
    ROUND(SUM(Quantity * UnitPrice), 2) AS total_revenue,
    COUNT(DISTINCT InvoiceNo) AS total_invoices
FROM sales
WHERE Country <> 'United Kingdom'
  AND InvoiceNo NOT LIKE 'C%'
GROUP BY Country
ORDER BY total_revenue DESC
LIMIT 10;
"""

result = pd.read_sql_query(query, conn)
print(result.to_string(index=False))

    Country  total_revenue  total_invoices
Netherlands      285446.34              95
       EIRE      283453.96             288
    Germany      228867.14             457
     France      209715.11             392
  Australia      138521.31              57
      Spain       61577.11              90
Switzerland       57089.90              54
    Belgium       41196.34              98
     Sweden       38378.33              36
      Japan       37416.37              19

**Key Findings:**
- The Netherlands ranked first, generating 285,446.34 across 95 invoices.
- EIRE ranked second, generating 283,453.96 across 288 invoices.
- Germany ranked third, generating 228,867.14 across 457 invoices.
- France ranked fourth, generating 209,715.11 across 392 invoices.
- Australia ranked fifth, generating 138,521.31 across 57 invoices.
- Germany recorded the highest invoice count among the ten countries, while the Netherlands generated the highest revenue.

**Business Interpretation:** The results identify the Netherlands, EIRE, Germany, France, and Australia as important international markets by revenue. Differences between revenue and invoice counts suggest that transaction frequency alone does not explain market performance. Further investigation could examine average order value, customer purchasing patterns, and opportunities to grow these markets.

**Limitation:** This analysis covers only the ten highest-revenue countries outside the United Kingdom. Revenue does not establish profitability or market growth potential.

**Status:** SQL analysis completed; findings documented.

### Business Question 7: Do Customers Make Repeat Purchases?

**Objective:** Determine how many customers made purchases across multiple invoices compared with customers who purchased only once.

**Method:** SQL was used to count distinct non-cancelled invoices for each identified customer. Customers with more than one invoice were classified as repeat customers, while those with exactly one invoice were classified as one-time customers.

In [ ]:

query = """
WITH customer_invoices AS (
    SELECT
        CustomerID,
        COUNT(DISTINCT InvoiceNo) AS total_invoices
    FROM sales
    WHERE CustomerID IS NOT NULL
      AND InvoiceNo NOT LIKE 'C%'
    GROUP BY CustomerID
)
SELECT
    COUNT(*) AS total_customers,
    SUM(
        CASE WHEN total_invoices > 1
             THEN 1 ELSE 0 END
    ) AS repeat_customers,
    SUM(
        CASE WHEN total_invoices = 1
             THEN 1 ELSE 0 END
    ) AS one_time_customers,
    ROUND(
        100.0 * SUM(
            CASE WHEN total_invoices > 1
                 THEN 1 ELSE 0 END
        ) / COUNT(*), 2
    ) AS repeat_customer_percentage
FROM customer_invoices;
"""

result = pd.read_sql_query(query, conn)
print(result.to_string(index=False))

 total_customers  repeat_customers  one_time_customers  repeat_customer_percentage
            4339              2845                1494                       65.57

**Key Findings:**
- Total customers analyzed: 4,339.
- Repeat customers: 2,845 (65.57%).
- One-time customers: 1,494 (34.43%).

**Business Interpretation:** Most identified customers made purchases across multiple invoices during the observed period. However, approximately one-third purchased only once. The business could investigate why these customers did not return and evaluate appropriate strategies to encourage subsequent purchases.

**Limitation:** Repeat purchasing across the dataset period does not establish customer retention within a specific time interval or predict future purchasing behavior.

**Status:** SQL analysis completed; findings documented.

### Business Question 8: Which Products Generate the Most Revenue?

**Objective:** Identify the products generating the highest recorded revenue to understand the merchandise and charges contributing most to business sales.

**Method:** SQL aggregation of `Quantity × UnitPrice`, grouped by product code and description, ranked by revenue in descending order.

In [ ]:

query = """
SELECT
    StockCode,
    Description,
    ROUND(SUM(Quantity * UnitPrice), 2) AS total_revenue,
    SUM(Quantity) AS total_quantity_sold,
    COUNT(DISTINCT InvoiceNo) AS total_invoices
FROM sales
WHERE InvoiceNo NOT LIKE 'C%'
  AND Quantity > 0
  AND UnitPrice > 0
  AND Description IS NOT NULL
GROUP BY StockCode, Description
ORDER BY total_revenue DESC
LIMIT 10;
"""

result = pd.read_sql_query(query, conn)
print(result.to_string(index=False))

StockCode                        Description  total_revenue  total_quantity_sold  total_invoices
      DOT                     DOTCOM POSTAGE      206248.77                  706             706
    22423           REGENCY CAKESTAND 3 TIER      174484.74                13879            1988
    23843        PAPER CRAFT , LITTLE BIRDIE      168469.60                80995               1
   85123A WHITE HANGING HEART T-LIGHT HOLDER      104340.29                37599            2189
    47566                      PARTY BUNTING       99504.33                18295            1685
   85099B            JUMBO BAG RED RETROSPOT       94340.05                48474            2089
    23166     MEDIUM CERAMIC TOP STORAGE JAR       81700.92                78033             247
        M                             Manual       78110.27                 7224             289
     POST                            POSTAGE       78101.88                 3150            1126
    23084                 RABBIT NIGHT LIGHT       66964.99                30788             994

**Key Findings:**
- DOTCOM POSTAGE ranked first, with recorded revenue of 206,248.77.
- REGENCY CAKESTAND 3 TIER ranked second, with revenue of 174,484.74.
- PAPER CRAFT, LITTLE BIRDIE ranked third, with revenue of 168,469.60.
- WHITE HANGING HEART T-LIGHT HOLDER and PARTY BUNTING also appeared among the leading revenue entries.

**Business Interpretation:** Revenue is concentrated among a small group of high-ranking entries. However, postage and other non-merchandise charges must be distinguished from physical products before drawing conclusions about the best-performing merchandise.

**Status:** Initial SQL analysis completed. Further classification of merchandise versus service-related charges is required before finalizing product-level conclusions.

### Business Question 9: Which Physical Products Generate the Most Revenue?

**Objective:** Identify the merchandise items generating the highest revenue, excluding postage charges.

**Method:** SQL aggregation of `Quantity × UnitPrice`, grouped by stock code and product description. Cancelled invoices and postage entries were excluded, and the results were ranked by revenue in descending order.

In [ ]:
query = """
SELECT
    StockCode,
    Description,
    ROUND(SUM(Quantity * UnitPrice), 2) AS total_revenue,
    SUM(Quantity) AS total_quantity
FROM sales
WHERE InvoiceNo NOT LIKE 'C%'
  AND Description IS NOT NULL
  AND Description NOT LIKE '%POSTAGE%'
GROUP BY StockCode, Description
ORDER BY total_revenue DESC
LIMIT 10;
"""

result = pd.read_sql_query(query, conn)
print(result.to_string(index=False))

StockCode                        Description  total_revenue  total_quantity
    22423           REGENCY CAKESTAND 3 TIER      174484.74           13890
    23843        PAPER CRAFT , LITTLE BIRDIE      168469.60           80995
   85123A WHITE HANGING HEART T-LIGHT HOLDER      104340.29           37603
    47566                      PARTY BUNTING       99504.33           18299
   85099B            JUMBO BAG RED RETROSPOT       94340.05           48478
    23166     MEDIUM CERAMIC TOP STORAGE JAR       81700.92           78033
        M                             Manual       78110.27            7230
    23084                 RABBIT NIGHT LIGHT       66964.99           30788
    22086    PAPER CHAIN KIT 50'S CHRISTMAS        64952.29           19355
    84879      ASSORTED COLOUR BIRD ORNAMENT       59094.93           36461

**Key Findings:**
- REGENCY CAKESTAND 3 TIER ranked first, generating 174,484.74 in recorded revenue.
- PAPER CRAFT, LITTLE BIRDIE ranked second, generating 168,469.60.
- WHITE HANGING HEART T-LIGHT HOLDER ranked third, generating 104,340.29.
- PARTY BUNTING and JUMBO BAG RED RETROSPOT also ranked among the leading merchandise entries.

**Business Interpretation:** Revenue performance varies considerably across the leading products. The results identify merchandise that may warrant further investigation for inventory planning and product-level performance evaluation.

**Limitation:** These rankings measure revenue, not profitability. They do not account for product costs, and the query excludes postage and cancelled invoices but does not establish whether all other non-merchandise entries have been excluded.

**Status:** SQL analysis completed and findings documented.

### Business Question 10: Which Products Sell the Highest Quantities?

**Objective:** Identify the merchandise items with the highest net quantities sold to support inventory planning and product demand assessment.

**Method:** Use SQL to aggregate transaction quantities by stock code and product description, excluding cancelled invoices and postage entries.

**Business Relevance:** Understanding unit demand helps the business distinguish high-volume products from products that generate high revenue.

**Status:** Pending SQL execution and interpretation.

In [ ]:
query = """
SELECT
    StockCode,
    Description,
    SUM(Quantity) AS net_quantity_sold,
    ROUND(SUM(Quantity * UnitPrice), 2) AS total_revenue
FROM sales
WHERE InvoiceNo NOT LIKE 'C%'
  AND Description IS NOT NULL
  AND Description NOT LIKE '%POSTAGE%'
GROUP BY StockCode, Description
HAVING SUM(Quantity) > 0
ORDER BY net_quantity_sold DESC
LIMIT 10;
"""

result = pd.read_sql_query(query, conn)
print(result.to_string(index=False))

StockCode                        Description  net_quantity_sold  total_revenue
    23843        PAPER CRAFT , LITTLE BIRDIE              80995      168469.60
    23166     MEDIUM CERAMIC TOP STORAGE JAR              78033       81700.92
    84077  WORLD WAR 2 GLIDERS ASSTD DESIGNS              55047       13841.85
   85099B            JUMBO BAG RED RETROSPOT              48478       94340.05
   85123A WHITE HANGING HEART T-LIGHT HOLDER              37603      104340.29
    22197                     POPCORN HOLDER              36761       34298.87
    84879      ASSORTED COLOUR BIRD ORNAMENT              36461       59094.93
    21212    PACK OF 72 RETROSPOT CAKE CASES              36419       21259.10
    23084                 RABBIT NIGHT LIGHT              30788       66964.99
    22492            MINI PAINT SET VINTAGE               26633       16937.82

### Business Interpretation

The results show that product demand varies considerably across merchandise items. PAPER CRAFT, LITTLE BIRDIE recorded the highest net quantity sold, at 80,995 units, followed by MEDIUM CERAMIC TOP STORAGE JAR with 78,033 units.

However, high sales volume does not necessarily translate into high revenue. For example, WORLD WAR 2 GLIDERS ASSTD DESIGNS sold 55,047 units but generated only 13,841.85 in revenue. In comparison, WHITE HANGING HEART T-LIGHT HOLDER sold 37,603 units and generated 104,340.29.

These differences indicate that the business should consider both sales volume and revenue when evaluating product performance. High-volume products may warrant closer inventory monitoring, while high-revenue products deserve attention when assessing their contribution to sales.

**Business implication:** Use quantity sold to understand product movement and revenue to assess sales contribution. These measures should be considered together when making inventory and merchandising decisions.

**Limitation:** The analysis identifies historical sales volume, not profitability or future demand. Further analysis would be required to establish product costs, profit margins, and seasonal demand patterns.

## Business Question 11: How Does Average Order Value Differ Across Countries?

**Objective:** Compare average invoice revenue across countries to identify markets with higher-value transactions.

**Analytical Approach:** Use SQL to calculate invoice revenue and then determine the average invoice value for each country. Exclude cancelled invoices and use consistent transaction rules.

In [ ]:

query = """
WITH invoice_revenue AS (
    SELECT
        Country,
        InvoiceNo,
        SUM(Quantity * UnitPrice) AS invoice_value
    FROM sales
    WHERE InvoiceNo NOT LIKE 'C%'
    GROUP BY Country, InvoiceNo
)
SELECT
    Country,
    COUNT(*) AS invoice_count,
    ROUND(AVG(invoice_value), 2) AS average_order_value
FROM invoice_revenue
GROUP BY Country
HAVING COUNT(*) >= 10
ORDER BY average_order_value DESC
LIMIT 10;
"""

result = pd.read_sql_query(query, conn)
print(result.to_string(index=False))

    Country  invoice_count  average_order_value
Netherlands             95              3004.70
  Australia             57              2430.20
      Japan             19              1969.28
  Hong Kong             11              1426.53
     Sweden             36              1066.06
Switzerland             54              1057.22
    Denmark             18              1053.07
     Norway             36              1004.60
       EIRE            288               984.22
     Cyprus             16               849.40

### Findings

- **The Netherlands** recorded the highest average order value at **3,084.70** across 95 invoices.
- **Australia** ranked second at **2,430.20** across 57 invoices.
- **Japan** ranked third at **1,969.28** across 19 invoices.
- **Hong Kong** recorded an average order value of **1,426.53** across 11 invoices.
- **EIRE** had a lower average order value of **984.22**, despite having 288 invoices in the dataset.

### Business Interpretation

The results suggest that average transaction value varies considerably across countries. The Netherlands, Australia, and Japan generated higher average invoice values than EIRE, which recorded a much larger number of invoices. This indicates that markets with more transactions do not necessarily have the highest average order value.

### Business Recommendation

Investigate why the Netherlands, Australia, and Japan have higher average invoice values. Compare their product mix, customer purchasing patterns, and shipping-related costs before deciding where to focus sales-growth efforts. Use both average order value and total revenue when prioritizing markets.

### Limitation

These figures represent average invoice values, not profit or customer lifetime value. They exclude cancelled invoices, but returns and negative quantities may still affect the results. The query also includes only countries with at least 10 invoices. Confirm the dataset's currency and validate return treatment before making final financial decisions.

## Business Question 12: Which Countries Have the Highest Cancellation Rates?

**Business Question:** Which countries have the highest cancellation rates?

**Objective:** Compare cancellation activity across countries to identify markets that may require further investigation.

**Analytical Approach:** Use SQL to count cancelled invoices and total invoices for each country, then calculate the cancellation rate as a percentage. Include countries with at least 10 invoices to reduce the influence of very small transaction counts.

In [ ]:
query = """
SELECT
    Country,
    COUNT(DISTINCT CASE
        WHEN InvoiceNo LIKE 'C%' THEN InvoiceNo
    END) AS cancelled_invoices,
    COUNT(DISTINCT InvoiceNo) AS total_invoices,
    ROUND(
        100.0 * COUNT(DISTINCT CASE
            WHEN InvoiceNo LIKE 'C%' THEN InvoiceNo
        END)
        / COUNT(DISTINCT InvoiceNo),
        2
    ) AS cancellation_rate_pct
FROM sales
GROUP BY Country
HAVING COUNT(DISTINCT InvoiceNo) >= 10
ORDER BY cancellation_rate_pct DESC
LIMIT 10;
"""

result = pd.read_sql_query(query, conn)
print(result.to_string(index=False))

        Country  cancelled_invoices  total_invoices  cancellation_rate_pct
          Malta                   5              10                  50.00
          Japan                   9              28                  32.14
          Italy                  17              55                  30.91
      Singapore                   3              10                  30.00
    Switzerland                  20              74                  27.03
      Hong Kong                   4              15                  26.67
        Germany                 146             603                  24.21
         Sweden                  10              46                  21.74
Channel Islands                   7              33                  21.21
         Poland                   5              24                  20.83

### Findings

- **Malta** recorded the highest cancellation rate at **50.00%**, with 5 cancelled invoices out of 10 total invoices.
- **Japan** ranked second at **32.14%**, with 9 cancelled invoices out of 28.
- **Italy** recorded a cancellation rate of **30.91%**, with 17 cancelled invoices out of 55.
- **Singapore** had a cancellation rate of **30.00%**, with 3 cancelled invoices out of 10.
- **Switzerland** recorded a rate of **27.03%**, with 20 cancelled invoices out of 74.
- **Germany** had 146 cancelled invoices out of 603, giving a cancellation rate of **24.21%**.

### Business Interpretation

Cancellation rates vary across countries. Malta has the highest rate in this result, but its 10 invoices represent a small sample. Germany has a lower rate than Malta but a substantially higher number of cancelled invoices. Therefore, both the cancellation rate and the number of cancelled invoices are important when assessing the scale of the issue.

### Business Recommendation

Investigate cancellation patterns in countries with high rates, beginning with Malta, Japan, and Italy. Also examine Germany because of its larger cancellation count. Before taking action, compare cancellation reasons, products, customer patterns, and invoice dates to determine whether there are recurring causes.

### Limitation

This analysis identifies invoices whose numbers begin with `C` and compares them with all distinct invoice numbers recorded for each country. It does not prove why cancellations occurred or whether they were avoidable. Countries with fewer than 10 invoices are excluded, and rates based on small invoice counts may be unstable.

### Question 13: What is the Overall Revenue Generated?

**Objective:** Establish the overall net transaction value and clarify how cancellation invoices affect the revenue calculation.

**Finding:** The SQL calculation returned £9,747,747.93 across all records and £10,644,560.42 after excluding cancellation invoices.

**Interpretation:** Excluding cancellation invoices increases the calculated value because some contain negative transactions.

**Limitation:** These figures are not yet reconciled with the Power BI result or the previously calculated customer-attributed revenue. The final revenue KPI must use one consistent definition.

**Next step:** Reconcile the SQL and Power BI calculations before publishing the dashboard.